### ISSUE TITLE
Cannot register plugin for multiple connections

### ISSUE THREAD

**Issue by garbles9100** [fknop/hapi-pagination#44]
In /lib/index.js there is a check for server.connections.length !== 1. Why is this check necessary? I'm trying to use two connections for my hapi server and this error is preventing me from doing that. I see that you have a unit test for this check, but I'm not seeing where you utilize the connections in a way that having multiple would matter.

**Comment by fknop** [comment]
There was a issue/PR some time ago about this (https://github.com/fknop/hapi-pagination/pull/17).

The tests failed randomly so I made the choice to not publish it, no changes have been made to it since then. 

If you want you can try to start from this PR. I don't have time to look into this myself for 2weeks at least.
Of course I would be happy to take some time to review a PR.

**Comment by fknop** [comment]
Fixed https://github.com/fknop/hapi-pagination/pull/45
